package org.example;// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class LoginTest{
    private WebDriver driver;
    private Map<String, Object> vars;
    JavascriptExecutor js;
    @Before
    public void setUp() {
        driver = new ChromeDriver();
        js = (JavascriptExecutor) driver;
        vars = new HashMap<String, Object>();
    }
    @After
    public void tearDown() {
        driver.quit();
    }
    @Test
    public void loginTest() {
        // Test name: LoginTest
        // Step # | name | target | value
        // 1 | open | / |
        driver.get("https://www.e-bebek.com/");
        // 2 | setWindowSize | 974x1032 |
        driver.manage().window().setSize(new Dimension(974, 1032));
        // 3 | mouseOver | css=.swiper-slide:nth-child(2) .hero__wrapper-image > .ng-star-inserted |
        {
            WebElement element = driver.findElement(By.cssSelector(".swiper-slide:nth-child(2) .hero__wrapper-image > .ng-star-inserted"));
            Actions builder = new Actions(driver);
            builder.moveToElement(element).perform();
        }
        // 4 | click | id=lnkLoginNavNode |
        driver.findElement(By.id("lnkLoginNavNode")).click();
        // 5 | click | id=txtPhoneNumberMobile |
        driver.findElement(By.id("txtPhoneNumberMobile")).click();
        // 6 | type | id=txtPhoneNumberMobile | (505) 800 46 34
        driver.findElement(By.id("txtPhoneNumberMobile")).sendKeys("(505) 800 46 34");
        // 7 | click | id=btnSubmitLogin |
        driver.findElement(By.id("btnSubmitLogin")).click();
        // 8 | click | id=txtPassword |
        driver.findElement(By.id("txtPassword")).click();
        // 9 | type | id=txtPassword | 1012O.u.1012
        driver.findElement(By.id("txtPassword")).sendKeys("1012O.u.1012");
        // 10 | sendKeys | id=txtPassword | ${KEY_ENTER}
        driver.findElement(By.id("txtPassword")).sendKeys(Keys.ENTER);
        // 11 | mouseOver | css=.swiper-slide:nth-child(1) .hero__wrapper-image > .ng-star-inserted |
        {
            WebElement element = driver.findElement(By.cssSelector(".swiper-slide:nth-child(1) .hero__wrapper-image > .ng-star-inserted"));
            Actions builder = new Actions(driver);
            builder.moveToElement(element).perform();
        }
        // 12 | mouseOver | css=.swiper-slide:nth-child(1) .hero__wrapper-image > .ng-star-inserted |
        {
            WebElement element = driver.findElement(By.cssSelector(".swiper-slide:nth-child(1) .hero__wrapper-image > .ng-star-inserted"));
            Actions builder = new Actions(driver);
            builder.moveToElement(element).perform();
        }
        // 13 | mouseOut | css=.swiper-slide:nth-child(1) .hero__wrapper-image > .ng-star-inserted |
        {
            WebElement element = driver.findElement(By.tagName("body"));
            Actions builder = new Actions(driver);
            builder.moveToElement(element, 0, 0).perform();
        }
        // 14 | click | id=iconMiniCart |
        driver.findElement(By.id("iconMiniCart")).click();

        WebElement ele = driver.findElement(By.id("lnkLoginNavNode"));

        if(ele.isEnabled()){
            System.out.println("Giriş Yapılmış");
        }

    }
}
